name: Auto Merge Pull Requests

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    if: github.actor == 'github-actions' || github.actor == 'your-github-username'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Enable auto-merge for PR
      run: gh pr merge "$PR_URL" --merge --admin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_URL: ${{ github.event.pull_request.html_url }}